apiVersion: v1
kind: Service
metadata:
  name: vprodb # here this name is important because it should be same as in application.properties file,
spec:          # because that is the name of service in there.
  ports:
    - port: 3306
      targetPort: vprodb-port # the ports name in vprodbdep.yaml file
      protocol: TCP
  selector:
    app: vprodb # this should be same as the pod labels we gave in vprodbdep.yaml file
  type: ClusterIP
