apiVersion: v1
kind: Service
metadata:
  name: vprocache01 # here this name is important because it should be same as in application.properties file,
spec:               # because that is the name of service in there.
  ports:
    - port: 11211
      targetPort: vpromc-port # the ports name in mcdep.yaml file
      protocol: TCP
  selector:
    app: vpromc # pod label defined in mcdep.yaml file
  type: ClusterIP
