apiVersion: v1
kind: Service
metadata:
  name: vpromq01 # name from application.properties file
spec:
  ports:
    - port: 15672
      targetPort: vpromq01-port # targetPort name from rmq-dep.yaml file
      protocol: TCP
  selector:
    app: vpromq01 # pod label from rmq-dep.yaml file
  type: ClusterIP